name: Preprocess Dataset

on:
  push:
    paths:
      - 'winequality-red/**'
      - 'preprocessing/**'
      - 'requirements.txt'
      - '.github/workflows/preprocess.yml'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing
        run: |
          python -c "
import sys
sys.path.append('preprocessing')
import pandas as pd
from automate_FebieElfaladonna import preprocess_wine_data

df = preprocess_wine_data('winequality-red/winequality-red.csv')
df.to_csv('winequality_red_preprocessed.csv', index=False)
print('Dataset berhasil diproses dan disimpan.')
          "

      - name: Commit hasil preprocessing
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add winequality_red_preprocessed.csv
          git commit -m 'Update hasil preprocessing otomatis'
          git push
