name: Preprocess Dataset

on:
  push:
    paths:
      - 'winequality-red/**'
      - 'preprocessing/automate_FebieElfaladonna.py'
      - '.github/workflows/preprocess.yml'
      - 'requirements.txt'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_FebieElfaladonna.py

      - name: Commit hasil preprocessing
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add preprocessing/winequality_red_preprocessed.csv
          git commit -m 'Update hasil preprocessing otomatis' || echo "Nothing to commit"
          git push
